#!/bin/sh

export MESON_SOURCE_ROOT="$1"
export MESON_BUILD_ROOT="$2"

if [ "$(id -u)" -eq 0 ]; then
    export CARGO_HOME="${MESON_BUILD_ROOT}/cargo"
    if [ -e "${MESON_BUILD_ROOT}/target/release/butter" ] && [ -e "${MESON_BUILD_ROOT}/target/release/butterd" ]; then
        echo "cargo build skipped: running as root"
        exit 0
    fi
fi

cargo build --manifest-path "${MESON_SOURCE_ROOT}/Cargo.toml" \
            --target-dir "${MESON_BUILD_ROOT}/target" \
            --release
